name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Show current time in IST
        run: echo "The current time in India is $(TZ=Asia/Kolkata date)"
