name: Release Check for uat
on: 
  release:
    types: [published, edited, deleted]
    repository_dispatch:
         push:
           branches:
            - main
            - uat
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.event.client_payload.ref }}
#       - run: echo ${{ github.event.client_payload.sha }}
      
#       - name: Repository Dispatch
#         uses: peter-evans/repository-dispatch@v2
#         with:
#           token: ${{ secrets.PAT }}
#           repository: Subharanjan-Playground/Sample14
#           event-type: my-event
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - run: |
          echo ${{ github.event_name.ref_type }}
          echo ${{ github.event.release.id }}
          echo ${{ github.event_name }}
          echo "This event was triggered by" 
          echo ${{ github.actor }}
          echo "Tag name "${{ github.ref_name }}
          echo "Actor name "${{ github.triggering_actor }}
          echo ${{ github.ref }}
          echo ${{ github.event.release.github_ref }}
          echo "Release Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}" 
          echo "Release referred branch ${{ github.event.release.target_commitish }}"
